server:
  port: 9000

spring:
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/nifi
    username: nifi
    password: nifi123!
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

jwt:
  secret: dGVydXRlcnVib3p1LXZpbmNlbnQtc2VjcmV0LWtleT09

logging:
  level:
    root: INFO
